import re
from datetime import datetime
from pathlib import Path


ARTIFACTS_DIR = Path(__file__).resolve().with_name("artifacts")


def _clean_text(text):
    return " ".join((text or "").split())


def _split_sections(content):
    content = (content or "").strip()

    if not content:
        raise ValueError("Report content is empty.")

    sections = []
    current_title = ""
    current_lines = []

    for raw_line in content.splitlines():
        line = raw_line.strip()

        if not line:
            continue

        heading_match = re.match(
            r"^(?:#{1,3}\s*)?(?:section\s*\d+|раздел\s*\d+)?\s*[:.-]?\s*(.+)$",
            line,
            flags=re.IGNORECASE,
        )

        looks_like_heading = (
            len(line) <= 90
            and not line.startswith(("-", "*"))
            and (
                line.endswith(":")
                or re.match(r"^(?:#{1,3}|section|раздел|\d+[.)])", line, re.IGNORECASE)
            )
        )

        if looks_like_heading and heading_match:
            if current_title or current_lines:
                sections.append(
                    {
                        "title": _clean_text(current_title) or "Section",
                        "body": _clean_text(" ".join(current_lines)),
                    }
                )

            current_title = heading_match.group(1).strip(" #:.-")
            current_lines = []
            continue

        current_lines.append(line.strip(" -*\t"))

    if current_title or current_lines:
        sections.append(
            {
                "title": _clean_text(current_title) or "Main Part",
                "body": _clean_text(" ".join(current_lines)),
            }
        )

    if len(sections) >= 2:
        return sections

    paragraphs = [
        _clean_text(paragraph)
        for paragraph in re.split(r"\n{2,}", content)
        if paragraph.strip()
    ]

    if paragraphs:
        return [
            {
                "title": f"Section {index}",
                "body": paragraph,
            }
            for index, paragraph in enumerate(paragraphs, start=1)
        ]

    return [{"title": "Main Part", "body": _clean_text(content)}]


def _add_paragraphs(document, text):
    sentences = re.split(r"(?<=[.!?])\s+", _clean_text(text))
    current = []

    for sentence in sentences:
        if not sentence:
            continue

        current.append(sentence)

        if len(" ".join(current)) >= 450:
            document.add_paragraph(" ".join(current))
            current = []

    if current:
        document.add_paragraph(" ".join(current))


def generate_docx_report(title, content, output_path, metadata=None):
    try:
        from docx import Document
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.shared import Pt
    except ImportError as error:
        raise RuntimeError(
            "python-docx is not installed. Add python-docx to requirements.txt."
        ) from error

    metadata = metadata or {}
    title = _clean_text(title) or "PracticeAI Report"
    sections = _split_sections(content)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    document = Document()

    title_paragraph = document.add_paragraph()
    title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_paragraph.add_run(title)
    title_run.bold = True
    title_run.font.size = Pt(24)

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.add_run(f"Created: {datetime.now().strftime('%Y-%m-%d %H:%M')}")

    generated = document.add_paragraph()
    generated.alignment = WD_ALIGN_PARAGRAPH.CENTER
    generated.add_run("Generated by PracticeAI")

    document.add_page_break()

    intro_text = metadata.get("introduction") or (
        "This report summarizes the key information, analysis, and conclusions "
        "prepared from the provided request and available context."
    )
    conclusion_text = metadata.get("conclusion") or (
        "The report highlights the main findings and provides a concise basis "
        "for further discussion, study, or decision-making."
    )

    document.add_heading("Introduction", level=1)
    _add_paragraphs(document, intro_text)

    document.add_heading("Main Part", level=1)

    for section in sections:
        section_title = section.get("title") or "Section"
        section_body = section.get("body") or ""

        if not section_body:
            continue

        document.add_heading(section_title[:90], level=2)
        _add_paragraphs(document, section_body)

    document.add_heading("Conclusion", level=1)
    _add_paragraphs(document, conclusion_text)

    sources = metadata.get("sources") or []

    if sources:
        document.add_heading("Used Documents", level=1)

        for source in sources:
            document.add_paragraph(str(source), style="List Bullet")

    document.add_paragraph("Generated by PracticeAI")
    document.save(output_path)

    if not output_path.exists() or output_path.stat().st_size == 0:
        raise RuntimeError("DOCX file was not saved correctly.")

    return {
        "file_path": str(output_path),
        "sections_count": len([section for section in sections if section.get("body")]),
        "file_size": output_path.stat().st_size,
    }


def make_report_output_path():
    ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
    file_name = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    return ARTIFACTS_DIR / file_name
